/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ISingletonFactory } from "../ISingletonFactory";

export class ISingletonFactory__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISingletonFactory {
    return new Contract(address, _abi, signerOrProvider) as ISingletonFactory;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_initCode",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "_salt",
        type: "bytes32",
      },
    ],
    name: "deploy",
    outputs: [
      {
        internalType: "address payable",
        name: "createdContract",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
