/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPoster } from "./IPoster";
export type { Poster } from "./Poster";

export { IPoster__factory } from "./factories/IPoster__factory";
export { Poster__factory } from "./factories/Poster__factory";
